### PR TITLE
Force validation on submit to display errors based on state

### PR DESCRIPTION
**Pull request by wpears**
Prevents an issue when submitting too early with an accidental return could cause malformed requests

### CODE REVIEW

**Comment by awolfe76** [comment]
@wpears - I see #100 depends on this. From our conversation yesterday, were you going to update this PR to prevent submission until all fields are valid (disable the submit) to match other tools?

**Comment by wpears** [comment]
I'm on the fence about whether disabled-on-load is the best UX (leaning no), so at any rate, no changes in this PR.

**Comment by awolfe76** [comment]
I would like @designlanguage to take a look at this too before merging.

It's not that I'm against this pattern but it definitely isn't consistent with other tools, including the platform UI where we have the submission disabled on the signature until the checkbox is checked. (Check digit also doesn't allow for submission until inputs are valid.)

If we choose this pattern over the existing, which is fine, we need to update both check digit and the platform UI to match.

**Comment by designlanguage** [comment]
I'm pro-consistency with our patterns.

The calculate button currently becomes inactive when incorrect data is entered anyway, and having no data entered should be treated similarly.

Additionally, when we click the "calculate" button without data entered, the error that's kicked back can't really tell us anything unique/helpful. The errors that show up in each field when incorrect data is entered already do a good job of that in context.

**Comment by wpears** [comment]
@awolfe76 @designlanguage kk, form disabled if any inputs are empty, at any time (along with when validation fails on submit or blur).

**Pull request merged**
